### ISSUE TITLE
android-vnc-server doesn't work on x86 android ports

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xgenvn/android-vnc-server#15]
```
What steps will reproduce the problem?
1. Run the binary on android-x86 ports 

It will be nice if the x86 binary is also available on the Downloads page. 

```

Original issue reported on code.google.com by `puneet.y...@gmail.com` on 6 Jun 2010 at 6:58

**Comment by mikespax** [comment]
I guess there's no simple way to do this for someone who doesn't want to get into code? Just looking to get VNC on my x86 VM installation.
